language: node_js
node_js:
  - '8.9'
before_install:
  - openssl aes-256-cbc -K $encrypted_aea5b6b08514_key -iv $encrypted_aea5b6b08514_iv -in src/config.ts.enc -out src/config.ts -d
before_script:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
before_deploy:
  - npm run firebase:predeploy
  - npm install -g firebase-tools
  - if [[ $TRAVIS_BRANCH =~ ^master$ ]] ; then npm run firebase:prod && export TARGET=api ; fi
  - if [[ $TRAVIS_BRANCH =~ ^rc-[0-9].[0-9].[0-9]$ ]] ; then npm run firebase:next && export TARGET=next ; fi
  - if [[ $TRAVIS_BRANCH =~ ^develop$ ]] ; then npm run firebase:devl && export TARGET=devl ; fi
deploy:
  provider: script
  script:
    firebase deploy --only functions:${TARGET} --token=${FIREBASE_API_TOKEN}
  skip_cleanup: true
  on:
    branch:
      - master
      - /^rc-[0-9].[0-9].[0-9]$/
      - develop
notifications:
  email:
    on_failure: change
    on_success: change
env:
  global:
    # FIREBASE_API_TOKEN
    - secure: dku/gnqIaBaH2BGZhFtnAd21SY1fjUVq6csAMVeogTbOEGqq7YQWghQjw6++E3cbr0DyD29EtPw1OGu32IuLs1i2i8xCRmuWun7ur/joSLjG2aZzihxIp6ncvueuSHATeVg5KpFxdxIO5BWNdjypo6k1GACiHkxdC7e4D62duiTo2v7liRZ0mlZV/KHdON3NyzDFqsQ5IcZe4tWHH+Jmbtde5pVia8wbYTfB/HJfy3oXP7AaNHWUtIkRKOobUqozx/xcH8JqDRxMZa/c9OajJNBk3piyGgZ+qbkE2xrT0u4dHfzLvddXv17zektb0beWhKK0j1nBCkbz/cG7WAt4gUQVGMkglwZ+7qgYvtOlpkaz+oveGiBLc8twevdRLtDq8/B0jeWOtJHi2Wvhy4Zb+5iOhxVxoApX828U80rdDACu+Hf3Ryig97QnRwsdk1I9cu99593JRfDEMD9dgK1Tlc2a7vNca3VaYgMxi1u0yfFm6Wo1Mov9PbZsHx+j0RTlhRrhDgAlz71xtmliovoIChjsYmr/dAcb71acsWtdX3vZJTQ30zlCmZBs3W4v764spoiDhrxsnmQ0jUwEoHxRtlcWxwSVgPmGyAD7bEiy2/fbUxUBChO+oKHAa3EOEHyLmqAvPLdGpA0pYoGKfQ+aqGC0WXsjocjJKzkGGepUT3w=
